USE dish2pass_db;

INSERT INTO RecipeTwos (spoonacularId, name, imageUrl, summary, type)
VALUES (137289, "Citrus-Rubbed Whole Duck", "https://spoonacular.com/recipeImages/137289-312x231.jpg", "Citrus-Rubbed Whole Duck might be just the main course you are searching for. One serving contains <b>3152 calories</b>, <b>90g of protein</b>, and <b>298g of fat</b>. This recipe serves 3.", "duck"), 
(23396, "Crispy Duck", "https://spoonacular.com/recipeImages/23396-312x231.jpg", "For <b>$1.61 per serving</b>, this recipe <b>covers 18%</b> of your daily requirements of vitamins and minerals. From preparation to the plate, this recipe takes about <b>45 minutes</b>.", "duck"),
(196282, "The Ultimate Turducken", "https://spoonacular.com/recipeImages/196282-312x231.jpg", "A mixture of chicken, duck, bulk sausage meat, and a handful of other ingredients are all it takes to make this recipe so tasty. All things considered, we decided this recipe <b>deserves a spoonacular score of 81%</b>.", "duck"),
(74720, "Slow-roasted Duck With Spiced Sour Cherry Sauce", "https://spoonacular.com/recipeImages/74720-312x231.jpg", "This gluten free recipe has <b>621 calories</b>, <b>15g of protein</b>, and <b>58g of fat</b> per serving. Head to the store and pick up pasture-raised duck, ghee, onion, and a few other things to make it today.", "duck"),
(619797, "Roasted Duck with Apples", "https://spoonacular.com/recipeImages/619797-312x231.jpg", "You could follow this main course with the <a href=\"https://spoonacular.com/recipes/candy-corn-cupcakes-63881\">Candy Corn Cupcakes</a> as a dessert. It is a good option if you're following a <b>caveman, gluten free, dairy free, and primal</b> diet. ", "duck"),
(670998, "Italian Wedding Soup", "https://spoonacular.com/recipeImages/670998-312x231.jpg", "Italian Wedding Soup is a <b>dairy free</b> soup. This recipe serves 29. One serving contains <b>51 calories</b>, <b>2g of protein</b>, and <b>0g of fat</b>.", "pasta"),
(76953, "Spaghetti With Pecorino Romano And Black Pepper", "https://spoonacular.com/recipeImages/76953-312x231.jpg", "You can never have too many main course recipes, so give Spaghetti With Pecorino Romano And Black Pepper a try. Watching your figure? This vegetarian recipe has <b>1979 calories</b>, <b>83g of protein</b>, and <b>26g of fat</b> per serving.", "pasta"),
(592424, "Antipasto Pasta", "https://spoonacular.com/recipeImages/592424-312x231.jpg", "Antipasto Pastan is a <b>dairy free</b> side dish. One serving contains <b>274 calories</b>, <b>8g of protein</b>, and <b>6g of fat</b>.", "pasta"),
(591703, "Spaghetti and Meatballs", "https://spoonacular.com/recipeImages/591703-312x231.jpg", "This recipe makes 6 servings with <b>437 calories</b>, <b>21g of protein</b>, and <b>13g of fat</b> each. If you have marinara 2.52, meatballs 5.28, spaghetti 1.22, and a few other ingredients on hand, you can make it.", "pasta"),
(393974, "Sausage 'n' Black Bean Pasta", "https://spoonacular.com/recipeImages/393974-312x231.jpg", "From preparation to the plate, this recipe takes approximately <b>20 minutes</b>. If you have beans, jalapeno jack pasta mix, sausage, and a few other ingredients on hand, you can make it.", "pasta"),
(207577, "Barbecue Chicken Sandwiches", "https://spoonacular.com/recipeImages/207577-312x231.jpg", "Barbecue Chicken Sandwiches might be just the main course you are searching for. This recipe serves 4. Watching your figure? This dairy free recipe has <b>633 calories</b>, <b>47g of protein</b>, and <b>25g of fat</b> per serving.", "burger"),
(172628, "Kalua Pork Sandwiches", "https://spoonacular.com/recipeImages/172628-312x231.jpg", "Slow-Cooker Kalua Pork Sandwiches is a <b>dairy free</b> main course. This recipe makes 16 servings with <b>567 calories</b>, <b>33g of protein</b>, and <b>38g of fat</b> each.", "burger"),
(610808, "Spicy Tomato Burger", "https://spoonacular.com/recipeImages/610808-312x231.jpg", "Spicy Tomato Burger might be just the main course you are searching for. This recipe makes 4 servings with <b>308 calories</b>, <b>30g of protein</b>, and <b>8g of fat</b> each.", "burger"),
(659316, "Saucy Shredded Barbecue Chicken", "https://spoonacular.com/recipeImages/659316-312x231.jpg", "Saucy Shredded Barbecue Chicken might be just the <b>American</b> recipe you are searching for. This recipe serves 4 and costs $1.8 per serving. One serving contains <b>395 calories</b>, <b>29g of protein</b>, and <b>5g of fat</b>.", "burger"),
(470047, "Slow Cooker Pulled Pork", "https://spoonacular.com/recipeImages/470047-312x231.jpg", "Slow Cooker Pulled Pork might be just the main course you are searching for. This recipe serves 8 and costs $1.59 per serving.", "burger");

INSERT INTO favorites (spoonacularId, name, imageUrl, summary, type)
VALUES (137289, "Citrus-Rubbed Whole Duck", "https://spoonacular.com/recipeImages/137289-312x231.jpg", "Citrus-Rubbed Whole Duck might be just the main course you are searching for. One serving contains <b>3152 calories</b>, <b>90g of protein</b>, and <b>298g of fat</b>. This recipe serves 3.", "duck"), 
(76953, "Spaghetti With Pecorino Romano And Black Pepper", "https://spoonacular.com/recipeImages/76953-312x231.jpg", "You can never have too many main course recipes, so give Spaghetti With Pecorino Romano And Black Pepper a try. Watching your figure? This vegetarian recipe has <b>1979 calories</b>, <b>83g of protein</b>, and <b>26g of fat</b> per serving.", "pasta"),
(393974, "Sausage 'n' Black Bean Pasta", "https://spoonacular.com/recipeImages/393974-312x231.jpg", "From preparation to the plate, this recipe takes approximately <b>20 minutes</b>. If you have beans, jalapeno jack pasta mix, sausage, and a few other ingredients on hand, you can make it.", "pasta"),
(207577, "Barbecue Chicken Sandwiches", "https://spoonacular.com/recipeImages/207577-312x231.jpg", "Barbecue Chicken Sandwiches might be just the main course you are searching for. This recipe serves 4. Watching your figure? This dairy free recipe has <b>633 calories</b>, <b>47g of protein</b>, and <b>25g of fat</b> per serving.", "burger"),
(172628, "Kalua Pork Sandwiches", "https://spoonacular.com/recipeImages/172628-312x231.jpg", "Slow-Cooker Kalua Pork Sandwiches is a <b>dairy free</b> main course. This recipe makes 16 servings with <b>567 calories</b>, <b>33g of protein</b>, and <b>38g of fat</b> each.", "burger");